language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -e .
before_script:
  - pip install -r requirements.txt
script:
  - tox -e py
after_success:
  - pip install python-coveralls
  - coveralls
